using LegoGamesCheatCodeInputter.Models.Games.Interfaces;

namespace LegoGamesCheatCodeInputter.Models.Games
{
    public sealed class LegoStarWarsTheCompleteSaga : IGame
    {
        public string Title { get; } = "Lego Star Wars: The Complete Saga";

        public IReadOnlyList<CheatCode> Codes { get; } =
            new List<CheatCode>
            {
                new CheatCode { Code = "DVY683", Description = "4-LOM" },
                new CheatCode { Code = "ECU428", Description = "Aayla Secura" },
                new CheatCode { Code = "MUN486", Description = "Adi Mundi" },
                new CheatCode { Code = "ACK646", Description = "Admiral Ackbar" },
                new CheatCode { Code = "HJI667", Description = "Anakin Skywalker (Ghost)" },
                new CheatCode { Code = "AUJ261", Description = "Battle Droid" },
                new CheatCode { Code = "KPF958", Description = "Battle Droid (Commander)" },
                new CheatCode { Code = "NJK995", Description = "Battle Droid (Geonosis)" },
                new CheatCode { Code = "HWY633", Description = "Battle Droid (Security)" },
                new CheatCode { Code = "BHH538", Description = "Beach Trooper" },
                new CheatCode { Code = "BENGH8", Description = "Ben Kenobi (Ghost)" },
                new CheatCode { Code = "CDT859", Description = "Bespin Guard" },
                new CheatCode { Code = "MMN372", Description = "Bib Fortuna" },
                new CheatCode { Code = "BOBA00", Description = "Boba Fett" },
                new CheatCode { Code = "GGF539", Description = "Boba Fett (Boy)" },
                new CheatCode { Code = "HHY697", Description = "Boss Nass" },
                new CheatCode { Code = "HYR849", Description = "Bossk" },
                new CheatCode { Code = "BKJ462", Description = "Bounty Hunter Rockets" },
                new CheatCode { Code = "QRN714", Description = "Captain Tarpals" },
                new CheatCode { Code = "DHY782", Description = "Character Studs" },
                new CheatCode { Code = "BDE289", Description = "Clone" },
                new CheatCode { Code = "XXD447", Description = "Clone (Episode 3 Pilot)" },
                new CheatCode { Code = "QYD793", Description = "Clone (Episode 3 Swamp)" },
                new CheatCode { Code = "NBU753", Description = "Clone (Episode 3 Walker)" },
                new CheatCode { Code = "VCT533", Description = "Clone (Episode 3)" },
                new CheatCode { Code = "NNB674", Description = "Clone Arcfighter" },
                new CheatCode { Code = "DDD748", Description = "Count Dooku" },
                new CheatCode { Code = "DRK328", Description = "Dark Side" },
                new CheatCode { Code = "EUK421", Description = "Darth Maul" },
                new CheatCode { Code = "NJK912", Description = "Death Star Trooper" },
                new CheatCode { Code = "BNL435", Description = "Deflect Bolts" },
                new CheatCode { Code = "GAR945", Description = "Dengar" },
                new CheatCode { Code = "JJU782", Description = "Dexter Jettster" },
                new CheatCode { Code = "HJU848", Description = "Disarm Troopers" },
                new CheatCode { Code = "BRJ437", Description = "Disguise" },
                new CheatCode { Code = "CCH677", Description = "Disguised Clone" },
                new CheatCode { Code = "AAB123", Description = "Droid Tri-Fighter" },
                new CheatCode { Code = "XCT333", Description = "Droideka" },
                new CheatCode { Code = "EWK785", Description = "Ewok" },
                new CheatCode { Code = "EXP912", Description = "Exploding Blaster Bolts" },
                new CheatCode { Code = "KJU233", Description = "Fast Build" },
                new CheatCode { Code = "BYY492", Description = "Fast Force" },
                new CheatCode { Code = "CLZ738", Description = "Force Grapple Leap" },
                new CheatCode { Code = "PUL966", Description = "Force Pull" },
                new CheatCode { Code = "NNM784", Description = "Gamorrean Guard" },
                new CheatCode { Code = "PMN576", Description = "General Grevious" },
                new CheatCode { Code = "HJY732", Description = "Geonosian" },
                new CheatCode { Code = "VYY985", Description = "Grand Moff Tarkin" },
                new CheatCode { Code = "ZZR636", Description = "Greedo" },
                new CheatCode { Code = "JHU423", Description = "Grievous' Bodyguard" },
                new CheatCode { Code = "KLA621", Description = "Han Solo (Hood)" },
                new CheatCode { Code = "GIJ989", Description = "IG-88" },
                new CheatCode { Code = "GUA850", Description = "Imperial Guard" },
                new CheatCode { Code = "KLP412", Description = "Imperial Officer" },
                new CheatCode { Code = "HUT845", Description = "Imperial Shuttle" },
                new CheatCode { Code = "BKJ857", Description = "Imperial Shuttle Pilot" },
                new CheatCode { Code = "YZFR1K", Description = "Imperial Spy" },
                new CheatCode { Code = "NUJ866", Description = "Infinite Torpedoes" },
                new CheatCode { Code = "HS9K44", Description = "Invincibility" },
                new CheatCode { Code = "KLJ897", Description = "Jango Fett" },
                new CheatCode { Code = "NVU859", Description = "Jawa" },
                new CheatCode { Code = "MUN486", Description = "Ki-Adi Mundi" },
                new CheatCode { Code = "TFI888", Description = "Kit Fisto" },
                new CheatCode { Code = "KLG412", Description = "Lama Su" },
                new CheatCode { Code = "BVH785", Description = "Lobot" },
                new CheatCode { Code = "TTY463", Description = "Luke Skywalker (Hoth)" },
                new CheatCode { Code = "LUM521", Description = "Luminara" },
                new CheatCode { Code = "JKD867", Description = "Mace Windu (Episode 3)" },
                new CheatCode { Code = "FBM152", Description = "Minikit Detector" },
                new CheatCode { Code = "VBJ322", Description = "Padme" },
                new CheatCode { Code = "PPP555", Description = "Palace Guard" },
                new CheatCode { Code = "PER894", Description = "Perfect Deflect" },
                new CheatCode { Code = "RTD428", Description = "Pit Droid" },
                new CheatCode { Code = "PLK689", Description = "Plo Koon" },
                new CheatCode { Code = "PMN904", Description = "Poo Money" },
                new CheatCode { Code = "FBM834", Description = "Power Brick Detector" },
                new CheatCode { Code = "QQY843", Description = "Princess Leia (Prisoner)" },
                new CheatCode { Code = "EVILR2", Description = "R2-Q5 Droid" },
                new CheatCode { Code = "BKL123", Description = "Rebel Pilot" },
                new CheatCode { Code = "DHV940", Description = "Rebel Trooper" },
                new CheatCode { Code = "GHR673", Description = "Rebel Trooper (Hoth)" },
                new CheatCode { Code = "528HBB", Description = "Regenerate Hearts" },
                new CheatCode { Code = "YUF634", Description = "Royal Guard" },
                new CheatCode { Code = "CBR954", Description = "Sandtrooper" },
                new CheatCode { Code = "VXZ123", Description = "Score x10" },
                new CheatCode { Code = "HBF899", Description = "Score x2" },
                new CheatCode { Code = "DQY857", Description = "Score x4" },
                new CheatCode { Code = "NMP499", Description = "Score x6" },
                new CheatCode { Code = "XXY99G", Description = "Score x8" },
                new CheatCode { Code = "THY432", Description = "Sebulba's Pod" },
                new CheatCode { Code = "DRX444", Description = "Self Destruct" },
                new CheatCode { Code = "KIT766", Description = "Shaak Ti" },
                new CheatCode { Code = "BYU785", Description = "Skiff Guard" },
                new CheatCode { Code = "HVT573", Description = "Snowtrooper" },
                new CheatCode { Code = "NBN431", Description = "Stormtrooper" },
                new CheatCode { Code = "VXZ193", Description = "Stud Magnet" },
                new CheatCode { Code = "R2D222", Description = "Super Astromech" },
                new CheatCode { Code = "HDD733", Description = "Super Battle Droid" },
                new CheatCode { Code = "HHD647", Description = "Super Blasters" },
                new CheatCode { Code = "ERF893", Description = "Super Ewok Catapult" },
                new CheatCode { Code = "SPRGNK", Description = "Super Gonk" },
                new CheatCode { Code = "SLM768", Description = "Super Jedi Slam" },
                new CheatCode { Code = "GHL978", Description = "Super Lightsabers" },
                new CheatCode { Code = "294NMB", Description = "Super Slap" },
                new CheatCode { Code = "THE931", Description = "Super Thermal Detonator" },
                new CheatCode { Code = "DFY111", Description = "Super Zapper" },
                new CheatCode { Code = "PRX482", Description = "Taun We" },
                new CheatCode { Code = "EMP666", Description = "The Emperor" },
                new CheatCode { Code = "HJH848", Description = "TIE Bomber" },
                new CheatCode { Code = "DBH897", Description = "TIE Fighter" },
                new CheatCode { Code = "BVNJ84", Description = "TIE Fighter (Darth Vader)" },
                new CheatCode { Code = "BBR334", Description = "TIE Fighter Pilot" },
                new CheatCode { Code = "INT729", Description = "TIE Interceptor" },
                new CheatCode { Code = "53NKH3", Description = "Tractor Beam" },
                new CheatCode { Code = "YYR778", Description = "Tusken Raider" },
                new CheatCode { Code = "CGF754", Description = "Ugnaught" },
                new CheatCode { Code = "SMA293", Description = "Vehicle Smart Bomb" },
                new CheatCode { Code = "BDC866", Description = "Vulture Droid" },
                new CheatCode { Code = "JKJ589", Description = "Walkie Talkie Disable" },
                new CheatCode { Code = "PLL967", Description = "Watto" },
                new CheatCode { Code = "BWK887", Description = "Wookiee" },
                new CheatCode { Code = "VVV429", Description = "Yoda (Ghost)" },
                new CheatCode { Code = "584HJF", Description = "Zam Wesell" },
                new CheatCode { Code = "UUU875", Description = "Zam's Speeder" },
            };
    }
}
