using LegoGamesCheatCodeInputter.Models.Games.Interfaces;

namespace LegoGamesCheatCodeInputter.Models.Games
{
    public sealed class LegoStarWarsThreeTheCloneWars : IGame
    {
        public string Title { get; } = "Lego Star Wars III: The Clone Wars";

        public IReadOnlyList<CheatCode> Codes { get; } =
            new List<CheatCode>
            {
                new CheatCode { Code = "2VG95B", Description = "Aayla Secura" },
                new CheatCode { Code = "G2BFEN", Description = "Adi Gallia" },
                new CheatCode { Code = "272Y9Q", Description = "Admiral Ackbar (Classic)" },
                new CheatCode { Code = "NG6PYX", Description = "Admiral Yularen" },
                new CheatCode { Code = "2VJ9TH", Description = "Ahsoka" },
                new CheatCode { Code = "F9VUYJ", Description = "Anakin Skywalker" },
                new CheatCode { Code = "9AA4DW", Description = "Anakin Skywalker (Geonosian Arena)" },
                new CheatCode { Code = "YG9DD7", Description = "Asajj Ventress" },
                new CheatCode { Code = "M2V1JV", Description = "Aurra Sing" },
                new CheatCode { Code = "GEHX6C", Description = "Bail Organa" },
                new CheatCode { Code = "BTVTZ5", Description = "Barriss Offee" },
                new CheatCode { Code = "5Y7MA4", Description = "Battle Droid" },
                new CheatCode { Code = "LSU4LJ", Description = "Battle Droid Commander" },
                new CheatCode { Code = "9U4TF3", Description = "Bib Fortuna" },
                new CheatCode { Code = "TY2BYJ", Description = "Boba Fett (Classic)" },
                new CheatCode { Code = "Q5Q39P", Description = "Boil" },
                new CheatCode { Code = "574226", Description = "C-3PO" },
                new CheatCode { Code = "NHME85", Description = "Cad Bane" },
                new CheatCode { Code = "D8SNGJ", Description = "Captain Antilles (Classic)" },
                new CheatCode { Code = "MW3QYH", Description = "Captain Rex" },
                new CheatCode { Code = "GD6FX3", Description = "Captain Typho" },
                new CheatCode { Code = "5C62YQ", Description = "Chancellor Palpatine" },
                new CheatCode { Code = "66UU3T", Description = "Chewbacca (Classic)" },
                new CheatCode { Code = "HQ7BVD", Description = "Clone Pilot" },
                new CheatCode { Code = "7GFNCQ", Description = "Clone Shadow Trooper (Classic)" },
                new CheatCode { Code = "NP5GTT", Description = "Clone Trooper" },
                new CheatCode { Code = "7CB6NS", Description = "Commander Bly" },
                new CheatCode { Code = "SMN259", Description = "Commander Cody" },
                new CheatCode { Code = "U25HFC", Description = "Commander Fil" },
                new CheatCode { Code = "JRPR2A", Description = "Commander Ponds" },
                new CheatCode { Code = "QEGU64", Description = "Commando Droid" },
                new CheatCode { Code = "5XZQSV", Description = "Commander Stone" },
                new CheatCode { Code = "LEWR7WM", Description = "Count Dooku" },
                new CheatCode { Code = "QH68AK", Description = "Darth Maul (Classic)" },
                new CheatCode { Code = "QXY5XN", Description = "Darth Sidius (Classic)" },
                new CheatCode { Code = "FM4JB7", Description = "Darth Vader (Classic)" },
                new CheatCode { Code = "NMJFBL", Description = "Darth Vader Battle Damaged (Classic)" },
                new CheatCode { Code = "MB9EMW", Description = "Dr. Nuvo Vindi" },
                new CheatCode { Code = "JB9E5S", Description = "Echo" },
                new CheatCode { Code = "WUFDYA", Description = "Eeth Koth" },
                new CheatCode { Code = "WSFZZQ", Description = "Gammorean Guard" },
                new CheatCode { Code = "7FNU4T", Description = "General Grievous" },
                new CheatCode { Code = "GAFZUD", Description = "Geonosian Guard" },
                new CheatCode { Code = "2C8NHP", Description = "Gold Super Battle Droid" },
                new CheatCode { Code = "C686PK", Description = "Gonk Droid" },
                new CheatCode { Code = "NH2405", Description = "Grand Moff Tarkin" },
                new CheatCode { Code = "FUW4C2", Description = "Greedo (Classic)" },
                new CheatCode { Code = "KFDBXF", Description = "Han Solo (Classic)" },
                new CheatCode { Code = "G65KJJ", Description = "Heavy Super Battle Droid" },
                new CheatCode { Code = "WXUTWY", Description = "Heavy Weapons Clone Trooper" },
                new CheatCode { Code = "4AXTY4", Description = "HELIOS 3D" },
                new CheatCode { Code = "EUB8UG", Description = "Hevy" },
                new CheatCode { Code = "5A7XYX", Description = "Hondo Hohnaka" },
                new CheatCode { Code = "EABPCP", Description = "IG-86" },
                new CheatCode { Code = "5W6FGD", Description = "Imperial Guard (Classic)" },
                new CheatCode { Code = "5KZQ4D", Description = "Jango Fett" },
                new CheatCode { Code = "MESPTS", Description = "Jar Jar Binks" },
                new CheatCode { Code = "AYREC9", Description = "Jek" },
                new CheatCode { Code = "HGBCTQ", Description = "Ki-Adi-Mundi" },
                new CheatCode { Code = "PYWJ6N", Description = "Kit Fisto" },
                new CheatCode { Code = "ERAEWE", Description = "Lando Calrissian (Classic)" },
                new CheatCode { Code = "SM3Y9B", Description = "LEP Servent Droid" },
                new CheatCode { Code = "3NEUXC", Description = "Lieutenant Thire" },
                new CheatCode { Code = "TKCYUZ", Description = "Lok Durd" },
                new CheatCode { Code = "PG73HF", Description = "Luke Skywalker (Classic)" },
                new CheatCode { Code = "MKUYQ8", Description = "Luminara Unduli" },
                new CheatCode { Code = "R35Y7N", Description = "Lurman Villager" },
                new CheatCode { Code = "V4WMJN", Description = "Luxury Droid" },
                new CheatCode { Code = "8NVRWJ", Description = "Mace Windu" },
                new CheatCode { Code = "2KEF2D", Description = "Magna-Guard" },
                new CheatCode { Code = "ZKXG43", Description = "Nahdar Vebb" },
                new CheatCode { Code = "BJB94J", Description = "Neimoidian" },
                new CheatCode { Code = "QFYXMC", Description = "Nute Gunray" },
                new CheatCode { Code = "J9HNF9", Description = "Obi-Wan Kenobi" },
                new CheatCode { Code = "FFBU5M", Description = "Obi-Wan Kenobi (Classic)" },
                new CheatCode { Code = "5U9FJK", Description = "Obi-Wan Kenobi (Geonosian Arena)" },
                new CheatCode { Code = "DB7ZQN", Description = "Onaconda Farr" },
                new CheatCode { Code = "SZ824Q", Description = "Padmé Amidala (Geonosian Arena)" },
                new CheatCode { Code = "8X87U6", Description = "Padmé Amidala" },
                new CheatCode { Code = "BH2EHU", Description = "Pirate Ruffian" },
                new CheatCode { Code = "BUD4VU", Description = "Plo Koon" },
                new CheatCode { Code = "4592WM", Description = "Poggle The Lesser" },
                new CheatCode { Code = "2D3D3L", Description = "Princess Leia (Classic)" },
                new CheatCode { Code = "ZQRN85", Description = "Queen Neeyutnee" },
                new CheatCode { Code = "LKHD3B", Description = "Qui-Gon Jinn (Classic)" },
                new CheatCode { Code = "RZ5HUV", Description = "R2-D2" },
                new CheatCode { Code = "Z87PAU", Description = "R3-S6" },
                new CheatCode { Code = "5MXSYA", Description = "R4-P17" },
                new CheatCode { Code = "7PMC3C", Description = "R6-H5" },
                new CheatCode { Code = "PZMQNK", Description = "Rebel Commando (Classic)" },
                new CheatCode { Code = "2KLW5R", Description = "Robonino" },
                new CheatCode { Code = "4PTP53", Description = "Rys" },
                new CheatCode { Code = "MELL07", Description = "Savage Opress" },
                new CheatCode { Code = "EPBPLK", Description = "Senate Commando" },
                new CheatCode { Code = "S4Y7VW", Description = "Senate Commando (Republic)" },
                new CheatCode { Code = "EA4E9S", Description = "Senator Kharrus" },
                new CheatCode { Code = "9Q7YCT", Description = "Senator Philo" },
                new CheatCode { Code = "G4N7C2", Description = "Shahan Alama" },
                new CheatCode { Code = "5C62YQ", Description = "Sionver Boll" },
                new CheatCode { Code = "HPE7PZ", Description = "Stormtrooper (Classic)" },
                new CheatCode { Code = "MJKDV5", Description = "Super Battle Droid" },
                new CheatCode { Code = "FYVSHD", Description = "Tee Watt Kaa" },
                new CheatCode { Code = "HEBHW5", Description = "Turk Falso" },
                new CheatCode { Code = "GC2XSA", Description = "Tusken Raider (Classic)" },
                new CheatCode { Code = "PE7FGD", Description = "TX-20" },
                new CheatCode { Code = "QGENFD", Description = "Undead Geonosian" },
                new CheatCode { Code = "EGQQ4V", Description = "Vader's Apprentice (Classic)" },
                new CheatCode { Code = "VRUVSZ", Description = "Wag Too" },
                new CheatCode { Code = "ZP8XVH", Description = "Wat Tambor" },
                new CheatCode { Code = "BNJE79", Description = "Waxer" },
                new CheatCode { Code = "DRGLWS", Description = "Wedge Antilles (Classic)" },
                new CheatCode { Code = "4VVYQV", Description = "Whorm Loathsom" },
                new CheatCode { Code = "MP9DRE", Description = "Workout Clone Trooper" },
                new CheatCode { Code = "CSQTMB", Description = "Yoda" },
                new CheatCode { Code = "C9PRKP", Description = "AAT" },
                new CheatCode { Code = "RCTFLV", Description = "Anakin's Jedi Starfighter" },
                new CheatCode { Code = "ZY3AE2", Description = "ARC-170 Starfighter" },
                new CheatCode { Code = "AA279H", Description = "AT-AP" },
                new CheatCode { Code = "Z7H46T", Description = "AT-RT" },
                new CheatCode { Code = "VBEZEZ", Description = "AT-TE" },
                new CheatCode { Code = "YMWV33", Description = "BARC Speeder" },
                new CheatCode { Code = "9MUTS2", Description = "Destroyer Droid" },
                new CheatCode { Code = "NACMGG", Description = "Dwarf Spider Droid" },
                new CheatCode { Code = "PJ2U3R", Description = "Geonosian Solar Sailor" },
                new CheatCode { Code = "EDENEC", Description = "Geonosian Starfighter" },
                new CheatCode { Code = "77QEJL", Description = "H-Type Nubian Yacht" },
                new CheatCode { Code = "T7XF9Z", Description = "Hailfire Droid" },
                new CheatCode { Code = "NPGG24", Description = "Hyena Bomber" },
                new CheatCode { Code = "HRX2UK", Description = "Jedi Shuttle" },
                new CheatCode { Code = "H68D3K", Description = "Kit Fisto's Jedi Starfighter" },
                new CheatCode { Code = "HJ5HHD", Description = "Magna-Guard Starfighter" },
                new CheatCode { Code = "BET7CU", Description = "Medical Frigate" },
                new CheatCode { Code = "S6GRNZ", Description = "MSE-6" },
                new CheatCode { Code = "6LT4QL", Description = "Neimoidian Shuttle" },
                new CheatCode { Code = "25FMVT", Description = "Obi-Wan's Jedi Starfighter" },
                new CheatCode { Code = "7NEC36", Description = "OG-9 Homing Spider Droid" },
                new CheatCode { Code = "Z567HR", Description = "Pirate Saucer" },
                new CheatCode { Code = "3NQGYL", Description = "Pirate Speeder Tank" },
                new CheatCode { Code = "L4LCDV", Description = "Plo Koon's Jedi Starfighter" },
                new CheatCode { Code = "U2T4SP", Description = "Probe Droid" },
                new CheatCode { Code = "BQCXWR", Description = "Republic Attack Shuttle" },
                new CheatCode { Code = "J3MFJZ", Description = "Republic Cruiser" },
                new CheatCode { Code = "J2JNDD", Description = "Republic Dropship" },
                new CheatCode { Code = "C7M3DU", Description = "Republic Gunship" },
                new CheatCode { Code = "P8Z9M5", Description = "RX-200 Tank" },
                new CheatCode { Code = "KDDQVD", Description = "Slave I" },
                new CheatCode { Code = "7RL23G", Description = "Soulless One" },
                new CheatCode { Code = "59UU88", Description = "STAP" },
                new CheatCode { Code = "3RE9XV", Description = "Starhawk Speeder Bike" },
                new CheatCode { Code = "XPY46K", Description = "Stealth Ship" },
                new CheatCode { Code = "RYLVNW", Description = "Super Tank" },
                new CheatCode { Code = "MHG3XB", Description = "The Halo" },
                new CheatCode { Code = "T4K5L4", Description = "The Twilight" },
                new CheatCode { Code = "JSBLJS", Description = "Trident Assault Craft" },
                new CheatCode { Code = "AKA9BB", Description = "V-19 Torrent Starfighter" },
                new CheatCode { Code = "7W7K7S", Description = "Vulture Droid" },
                new CheatCode { Code = "LQ2SVT", Description = "Xanadu Blood" },
                new CheatCode { Code = "XTL6Y3", Description = "Y-Wing Starfighter" },
                new CheatCode { Code = "YZPHUV", Description = "2x Studs" },
                new CheatCode { Code = "43T5E5", Description = "4x Studs" },
                new CheatCode { Code = "SEBHGR", Description = "6x Studs" },
                new CheatCode { Code = "BYFSAQ", Description = "8x Studs" },
                new CheatCode { Code = "N1CKR1", Description = "10x Studs" },
                new CheatCode { Code = "QD2C31", Description = "Character Studs" },
                new CheatCode { Code = "X1V4N2", Description = "Dark Side" },
                new CheatCode { Code = "C4ES4R", Description = "Dual Wield" },
                new CheatCode { Code = "GCHP7S", Description = "Fast Build" },
                new CheatCode { Code = "4GT3VQ", Description = "Glow In The Dark" },
                new CheatCode { Code = "J46P7A", Description = "Invincibility" },
                new CheatCode { Code = "CSD5NA", Description = "Minikit Detector" },
                new CheatCode { Code = "3F5L56", Description = "Perfect Deflect" },
                new CheatCode { Code = "N3R01A", Description = "Red Brick Detector" },
                new CheatCode { Code = "2D7JNS", Description = "Regenerate Hearts" },
                new CheatCode { Code = "6MZ5CH", Description = "Stud Magnet" },
                new CheatCode { Code = "BS828K", Description = "Super Saber Cut" },
                new CheatCode { Code = "B1D3W3", Description = "Super Speeders" },
            };
    }
}
