using LegoGamesCheatCodeInputter.Models.Games.Interfaces;

namespace LegoGamesCheatCodeInputter.Models.Games
{
    public sealed class LegoIndianaJonesTheOriginalAdventures : IGame
    {
        public string Title { get; } = "Lego Indiana Jones: The Original Adventures";

        public IReadOnlyList<CheatCode> Codes { get; } =
            new List<CheatCode>
            {
                new CheatCode { Code = "VIKED7", Description = "Artifact Detector" },
                new CheatCode { Code = "04EM94", Description = "Barranca" },
                new CheatCode { Code = "VNF59Q", Description = "Beep Beep" },
                new CheatCode { Code = "CHN3YU", Description = "Belloq (Desert)" },
                new CheatCode { Code = "TDR197", Description = "Belloq (Jungle)" },
                new CheatCode { Code = "VEO29L", Description = "Belloq (Priest)" },
                new CheatCode { Code = "8246RB", Description = "Boxer" },
                new CheatCode { Code = "B73EUA", Description = "British Commander" },
                new CheatCode { Code = "VJ5TI9", Description = "British Officer" },
                new CheatCode { Code = "DJ5I2W", Description = "British Trooper" },
                new CheatCode { Code = "VJ3TT3", Description = "Captain Katanga" },
                new CheatCode { Code = "VIES2R", Description = "Character Treasure" },
                new CheatCode { Code = "ENW936", Description = "Chatterlal" },
                new CheatCode { Code = "3NK48T", Description = "Chucin" },
                new CheatCode { Code = "2K9RKS", Description = "Colonel Dietrich" },
                new CheatCode { Code = "8EAL4H", Description = "Colonel Vogel" },
                new CheatCode { Code = "C7EJ21", Description = "Dancing Girl" },
                new CheatCode { Code = "12N68W", Description = "Desert Digger" },
                new CheatCode { Code = "2MK45O", Description = "Desert Enemy Officer" },
                new CheatCode { Code = "N48SF0", Description = "Desert Masked Bandit" },
                new CheatCode { Code = "3RF6YJ", Description = "Desert Monkey Man" },
                new CheatCode { Code = "4NSU7Q", Description = "Desert Soldier" },
                new CheatCode { Code = "1MK4RT", Description = "Desert Swordsman" },
                new CheatCode { Code = "VKRNS9", Description = "Disarm Enemies" },
                new CheatCode { Code = "4ID1N6", Description = "Disguises" },
                new CheatCode { Code = "3NFTU8", Description = "Donovan" },
                new CheatCode { Code = "JSNRT9", Description = "Dr. Schneider (Desert)" },
                new CheatCode { Code = "VMJ5US", Description = "Dr. Schneider (Officer)" },
                new CheatCode { Code = "S93Y5R", Description = "Enemy Bazookaman" },
                new CheatCode { Code = "VJ48W3", Description = "Enemy Butler" },
                new CheatCode { Code = "1MF94R", Description = "Enemy Communications Officer" },
                new CheatCode { Code = "VJ7R51", Description = "Enemy Guard" },
                new CheatCode { Code = "YR47WM", Description = "Enemy Guard (Nepal)" },
                new CheatCode { Code = "572E61", Description = "Enemy Officer" },
                new CheatCode { Code = "B84ELP", Description = "Enemy Pilot" },
                new CheatCode { Code = "V83SLO", Description = "Fast Build" },
                new CheatCode { Code = "378RS6", Description = "Fast Dig" },
                new CheatCode { Code = "FJ59WS", Description = "Fast Fix" },
                new CheatCode { Code = "V75YSP", Description = "Fedora" },
                new CheatCode { Code = "B1GW1F", Description = "Fertilizer" },
                new CheatCode { Code = "0GIN24", Description = "First Mate" },
                new CheatCode { Code = "NE6THI", Description = "Grail Knight" },
                new CheatCode { Code = "H0V1SS", Description = "Hovitos Tribesman" },
                new CheatCode { Code = "33GM7J", Description = "Ice Rink" },
                new CheatCode { Code = "4J8S4M", Description = "Indiana Jones (Disguised)" },
                new CheatCode { Code = "VJ85OS", Description = "Indiana Jones (Officer)" },
                new CheatCode { Code = "B83EA1", Description = "Invincibility" },
                new CheatCode { Code = "24PF34", Description = "Jungle Guide" },
                new CheatCode { Code = "WMO46L", Description = "Kaokan" },
                new CheatCode { Code = "3M29TJ", Description = "Kazim (Desert)" },
                new CheatCode { Code = "NRH23J", Description = "Kazim (Venice)" },
                new CheatCode { Code = "2NK479", Description = "Laoche" },
                new CheatCode { Code = "NFK5N2", Description = "Maharaja" },
                new CheatCode { Code = "13NS01", Description = "Major Toht" },
                new CheatCode { Code = "FJUR31", Description = "Mola Ram" },
                new CheatCode { Code = "2NKT72", Description = "Pankot Assassin" },
                new CheatCode { Code = "VN28RH", Description = "Pankot Guard" },
                new CheatCode { Code = "VUT673", Description = "Parcel Detector" },
                new CheatCode { Code = "WWQ1SA", Description = "Poo Treasure" },
                new CheatCode { Code = "KD48TN", Description = "Punjabi Dignitary" },
                new CheatCode { Code = "4682E1", Description = "Punjabi Village Elder" },
                new CheatCode { Code = "MDLP69", Description = "Regenerate Hearts" },
                new CheatCode { Code = "3X44AA", Description = "Secret Characters" },
                new CheatCode { Code = "VJ37WJ", Description = "Sherpa Brawler" },
                new CheatCode { Code = "ND762W", Description = "Sherpa Gunner" },
                new CheatCode { Code = "3HE85H", Description = "Silhouettes" },
                new CheatCode { Code = "0E3ENW", Description = "Slave Child" },
                new CheatCode { Code = "VN3R7S", Description = "Super Scream" },
                new CheatCode { Code = "0P1TA5", Description = "Super Slap" },
                new CheatCode { Code = "VM683E", Description = "Thuggee" },
                new CheatCode { Code = "CNH4RY", Description = "Thuggee Chatterlal" },
                new CheatCode { Code = "T2R3F9", Description = "Thuggee Priest" },
                new CheatCode { Code = "VBS7GW", Description = "Thuggee Slavedriver" },
                new CheatCode { Code = "H86LA2", Description = "Treasure Magnet" },
                new CheatCode { Code = "VI3PS8", Description = "Treasure x10" },
                new CheatCode { Code = "VM4TS9", Description = "Treasure x2" },
                new CheatCode { Code = "VLWEN3", Description = "Treasure x4" },
                new CheatCode { Code = "V84RYS", Description = "Treasure x6" },
                new CheatCode { Code = "A72E1M", Description = "Treasure x8" },
                new CheatCode { Code = "VK93R7", Description = "Willie (DJ)" },
                new CheatCode { Code = "MEN4IP", Description = "Willie (Pajamas)" },
                new CheatCode { Code = "3NSLT8", Description = "Wuhan" },
            };
    }
}
